global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'nginx-proxy'
    static_configs:
      - targets: ['nginx_proxy_exporter:9101']
  - job_name: 'nginx-storage'
    static_configs:
      - targets: ['nginx_storage_exporter:9102']
  - job_name: 'cockroach-nodes'
    metrics_path: /metrics
    static_configs:
      - targets:
          - crdb1:8091
          - crdb2:8092
          - crdb3:8093
          - crdb4:8094
          - crdb5:8095
